"""
Report Generator Tool
Formats research findings into structured markdown reports
"""

from typing import Dict, Any, List
from datetime import datetime


def report_generator(
    template: str,
    sections: Dict[str, Any],
    sources: List[Dict] = None
) -> Dict[str, Any]:
    """
    Generate a structured investment research report.

    Args:
        template: Report template type
        sections: Dictionary of report sections and content
        sources: List of sources used

    Returns:
        Dictionary with formatted report
    """

    try:
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

        report = f"""# Investment Research Report
**Generated by ARA-1 Autonomous Research Agent**
**Date:** {timestamp}
**Template:** {template}

---

## Executive Summary
{sections.get("executive_summary", "Not available")}

---

## Company Overview
{sections.get("company_overview", "Not available")}

---

## Financial Analysis
{sections.get("financial_analysis", "Not available")}

---

## Risk Assessment
{sections.get("risk_assessment", "Not available")}

---

## Competitive Position
{sections.get("competitive_position", "Not available")}

---

## Investment Outlook
{sections.get("outlook", "Not available")}

---

## Research Methodology Notes
{sections.get("methodology", "Standard multi-source research methodology applied")}

---

## Sources Used
"""
        if sources:
            for i, source in enumerate(sources, 1):
                report += f"{i}. {source.get('name', 'Unknown')} - {source.get('type', 'Unknown')} - Reliability Tier {source.get('tier', 'N/A')}\n"
        else:
            report += "Sources not specified\n"

        report += "\n---\n*This report was generated autonomously by ARA-1. All claims are grounded in retrieved source documents.*"

        return {
            "success": True,
            "report": report,
            "word_count": len(report.split()),
            "sections_included": list(sections.keys()),
            "sources_cited": len(sources) if sources else 0,
            "generated_at": timestamp,
            "source": "Report Generator",
            "reliability_tier": 1
        }

    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "report": None
        }